### PR TITLE
492 get_repos() for users

### LINKED ISSUE #492: Handle getting users' repos
I found a weird issue that only seems to impact only @ddsjoberg's repos 

```r
  git_stats <- GitStats::create_gitstats() |>
    GitStats::set_github_host(
      repos = "ddsjoberg/gtsummary",
      token = Sys.getenv("GITHUB_PAT")
    ) |>
    GitStats::get_repos(progress = TRUE)
```

Gives an error:

```r
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `UseMethod()`:
! no applicable method for 'filter' applied to an object of class "NULL"
```

### PR DESCRIPTION
**Pull request by maciekbanas**
Make possible `get_repos()` for individual users on GitHub and GitLab.

Closes #492

### CODE REVIEW

File: R/GitHostGitHub.R [hunk 1]
```diff
@@ -88,6 +88,25 @@ GitHostGitHub <- R6::R6Class(
       private$endpoints$repositories <- glue::glue("{private$api_url}/repos")
     },
 
+    # Set owner type
+    set_owner_type = function(owners) {
```
Comment (marcinkowskak) [inline R/GitHostGitHub.R:92]: When token doesn't have required scope, code crashed with unformative error instead of error: 

`✔ Set connection to GitHub.
ℹ [Host:GitHub][Engine:GraphQl][Scope:ddsjoberg] Pulling repositories...
Called from: graphql_engine$get_repos_from_org(org = org, type = type)
Browse[1]> c
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `UseMethod()`:
! no applicable method for 'filter' applied to an object of class "NULL"
Run `rlang::last_trace()` to see where the error occurred.`

image

**Review by marcinkowskak — CHANGES_REQUESTED** [review]

File: R/GitHostGitHub.R (hunk 1 above)
Comment (maciekbanas) [reply R/GitHostGitHub.R:92]: I will create a separate issue on that, as it is more generic problem, which should be solved when setting up hosts.

**Review by marcinkowskak — APPROVED** [review]
